package com.generation.progettospesupbackend.entities.model;

public enum Category
{
	FRUTTA_E_VERDURA,
	CARNE_E_PESCE,
	FORMAGGI_SALUMI_E_GASTRONOMIA,
	LATTE_BURRO_E_YOGURT,
	PANE_E_PASTICCERIA,
	PASTA_RISO_E_CEREALI,
	VEGETARIANO_E_VEGANO,
	SUGHI_SCATOLAME_E_CONDIMENTI,
	UOVA_FARINE_E_PREPARATI,
	CAFFE_TE_E_ZUCCHERO,
	COLAZIONE_DOLCIUMI_E_SNACK,
	SURGELATI_E_GELATI,
	ACQUA_E_BEVANDE,
	BIRRERIA_ED_ENOTECA,
	CURA_PERSONA,
	PULIZIA_DELLA_CASA,
	CURA_CASA,
	BIMBI_E_INFANZIA,
	AMICI_ANIMALI,
	GIARDINO_E_HOBBY
}
